/** NestJS DI tokens for Phase 1C — kept in one file so every injection site imports from the same place. */
export const AUTH_ENV = Symbol("AUTH_ENV");

export const USER_REPOSITORY = Symbol("USER_REPOSITORY");
export const EXTERNAL_AUTH_IDENTITY_REPOSITORY = Symbol("EXTERNAL_AUTH_IDENTITY_REPOSITORY");
export const EMERGENCY_ADMIN_CREDENTIAL_REPOSITORY = Symbol(
  "EMERGENCY_ADMIN_CREDENTIAL_REPOSITORY",
);
export const SESSION_REPOSITORY = Symbol("SESSION_REPOSITORY");
export const AUTH_LOCKOUT_STATE_REPOSITORY = Symbol("AUTH_LOCKOUT_STATE_REPOSITORY");
export const RECOVERY_REQUEST_REPOSITORY = Symbol("RECOVERY_REQUEST_REPOSITORY");
export const AUTH_EVENT_REPOSITORY = Symbol("AUTH_EVENT_REPOSITORY");
export const OIDC_CONFIGURATION = Symbol("OIDC_CONFIGURATION");
export const EMERGENCY_ADMIN_LOGIN_NOTIFIER = Symbol("EMERGENCY_ADMIN_LOGIN_NOTIFIER");
