import {
  ArrowLeftRight,
  Bell,
  BookMarked,
  BookOpen,
  Bot,
  Briefcase,
  CheckCircle,
  ClipboardCheck,
  Component,
  FileCheck,
  FileCog,
  FileStack,
  FileText,
  FolderOpen,
  GalleryVertical,
  GitCompare,
  History,
  Home,
  Image,
  LayoutGrid,
  LayoutList,
  LayoutPanelLeft,
  LayoutTemplate,
  LifeBuoy,
  Library,
  Link,
  ListChecks,
  ListTodo,
  ListTree,
  Map,
  Palette,
  Play,
  Plug,
  Rocket,
  ScanSearch,
  Search,
  Settings,
  ShieldAlert,
  ShieldCheck,
  SwatchBook,
  UserCog,
  Users,
  Wrench,
  type LucideIcon,
} from "lucide-react";

/**
 * Maps `ModuleRegistrySummary.iconReference` (a real, already-seeded field — every one of the 43
 * modules has carried one of these 43 exact kebab-case values since migration `00035`, chosen
 * to match `lucide-react`'s own naming convention even though no icon library was ever installed
 * to consume them) onto the real icon component. Wiring this up is what the design canvas
 * "Enterprise Plus" direction's icon-per-nav-item/icon-per-module treatment needed — the data
 * was already there, `lucide-react` was the missing piece.
 */
const ICON_MAP: Readonly<Record<string, LucideIcon>> = {
  home: Home,
  briefcase: Briefcase,
  "book-open": BookOpen,
  map: Map,
  "layout-list": LayoutList,
  "file-text": FileText,
  "file-check": FileCheck,
  library: Library,
  "gallery-vertical": GalleryVertical,
  palette: Palette,
  image: Image,
  "folder-open": FolderOpen,
  "swatch-book": SwatchBook,
  component: Component,
  "layout-grid": LayoutGrid,
  "layout-template": LayoutTemplate,
  "layout-panel-left": LayoutPanelLeft,
  play: Play,
  "check-circle": CheckCircle,
  "list-checks": ListChecks,
  users: Users,
  "shield-check": ShieldCheck,
  search: Search,
  link: Link,
  "file-stack": FileStack,
  bot: Bot,
  "file-cog": FileCog,
  "book-marked": BookMarked,
  "list-tree": ListTree,
  "list-todo": ListTodo,
  "clipboard-check": ClipboardCheck,
  "scan-search": ScanSearch,
  "git-compare": GitCompare,
  "arrow-left-right": ArrowLeftRight,
  wrench: Wrench,
  rocket: Rocket,
  history: History,
  "life-buoy": LifeBuoy,
  bell: Bell,
  "user-cog": UserCog,
  plug: Plug,
  settings: Settings,
  "shield-alert": ShieldAlert,
};

/** Falls back to `LayoutGrid` for a module whose `iconReference` is `null` or not one of the 43
 *  known values — never throws, since this reads real backend data across a network boundary. */
export function moduleIcon(iconReference: string | null): LucideIcon {
  return (iconReference && ICON_MAP[iconReference]) || LayoutGrid;
}
